v2solve:
  appsecurityclient:
    connection:
      server-end-point: "http://localhost:9570" 
      basic: true
      basic-credentials:
        username: saurinya@gmail.com
        password: admin
      oauth2: false
      oauth2-credentials:
        client-id:
        client-secret:
        issuer-domain:
  app:
    security:
      disable: true