spring:
  datasource:
    url: jdbc:postgresql://post-gres-sql-db/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# This is the logon setup for the 
# spring boot app before it serves the angular app
v2solve:    
  app:
    security:
      xframe-option: none
      cors:
        allowed-methods:
        - "*"
        allowed-origins:
        - "*"
        allowed-headers:
        - "*"
      authwhitelist: "/oidc-support**"
      basic:
        jdbc:
          enable: true
          usersByUsernameQuery: "select name as username,user_password as password,enabled from basic_auth_clients where name = ?"
          authoritiesByUsernameQuery: "select name as username,'ADMIN' as authority from basic_auth_clients where name = ?"
        enable: true
        realm: v2solve
        users:
          - username: admin 
            password: system
            roles: superuser
          - username: app_onboarder
            password: system
            roles: superuser
# From this point onwards is the client connection to the security server
  appsecurityclient:
    connection:
      server-end-point: "http://app-security-rest-app:9570"
      basic: true
      basic-credentials:
        username: ADMIN_CONSOLE
        password: secretsauce
#    authwhitelist: /index.html
logging:
  level:
    com:
      v2solve:
        app:
          security: DEBUG
server:
  port: 8080