# This is the logon setup for the 
# spring boot app before it serves the angular app
v2solve:    
  app:
    security:
      oauth2:
        enable: true
        client:
          registration:
            okta:
              provider: "https://dev-869380.okta.com"
              client-id: "0oam02zxsNkBAw5xo4x6"
              client-secret: "fzulYFMjBkGqQuGRgdxZjk4T_1V6iqzJuQc4tmfv"
              client-name: Okta
              scope:
              - email
              - profile
              - openid
          provider:
            okta:
              user-name-attribute: email
              issuer-uri: "https://dev-869380.okta.com"

# From this point onwards is the client connection to the security server
  appsecurityclient:
    connection:
      server-end-point: "http://localhost:9570" 
      basic: true
      basic-credentials:
        username: ADMIN_CONSOLE
        password: secretsauce
      oauth2: false
      oauth2-credentials:
        client-id:
        client-secret:
        issuer-domain:

#    authwhitelist: /index.html
logging:
  level:
    com:
      v2solve:
        app:
          security: DEBUG
server:
  port: 8080