version: '3'
volumes:
  v2solveappsecdbservice_data:
services:
  v2solveappsecdbservice:
    volumes:
      - v2solveappsecdbservice_data=/var/lib/postgresql/data/pgdata
    environment:
      - SUPER_CLIENT_ID=admin
      - POSTGRES_PASSWORD=systempass
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: "v2solve-app-sec-db:1.0"
#    ports:
#     - "5432:5432"
  v2solveappsecrestappservice:
    image: "v2solve-app-sec-rest-app:1.0"
    ports:
      - "9570:9570"
    environment:
      - v2solve.app.security.initializer.basic-auth-users[0].username=admin
      - v2solve.app.security.initializer.basic-auth-users[0].password=system
      - v2solve.app.security.initializer.basic-auth-users[1].username=app_onboarder
      - v2solve.app.security.initializer.basic-auth-users[1].password=boarder
      - spring.datasource.url=jdbc:postgresql://v2solveappsecdbservice/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=systempass