apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: post-gres-sql-db-deployment
spec:
  selector:
    matchLabels:
      app: post-gres-sql-db-deployment
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: post-gres-sql-db-deployment
    spec:
      containers:
      - name: appsecdb
        image: "appsecdb:1.0"
        ports:
        - containerPort: 5432
        env:
        - name: SUPER_CLIENT_ID
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "systempass"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"

---

apiVersion: v1
kind: Service
metadata:
  name: postgressqldb
spec:
  selector:
    app: post-gres-sql-db-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
      
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: app-security-rest-app-deployment
spec:
  selector:
    matchLabels:
      app: app-security-rest-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: app-security-rest-app
    spec:
      containers:
      - name: appsecrestapp
        image: "app-sec-rest-app:1.0"
        ports:
        - containerPort: 9570
        env:
        - name: "v2solve_app_security_initializer_basicAuthUsers_0_username"
          value: "admin"
        - name: "v2solve_app_security_initializer_basicAuthUsers_0_password"
          value: system
        - name: "v2solve_app_security_initializer_basicAuthUsers_1_username"
          value: "app_onboarder"
        - name: "v2solve_app_security_initializer_basicAuthUsers_1_password"
          value: "boarder"
        - name: "spring_datasource_url"
          value: "jdbc:postgresql://postgressqldb/postgres"
        - name: "spring_datasource_username"
          value: "postgres"
        - name: "spring_datasource_password"
          value: "systempass"

---

apiVersion: v1
kind: Service
metadata:
  name: app-security-rest-app-service
spec:
  type: NodePort
  selector:
    app: app-security-rest-app
  ports:
    - protocol: TCP
      port: 9570
      targetPort: 9570
      nodePort: 30080
