spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

##If want to see very extensive logging
#spring.jpa.properties.hibernate.generate_statistics=true
#logging.level.org.hibernate.type=trace
#logging.level.org.hibernate.stat=debug
v2solve:    
  app:
    security:
      xframe-option: none
      cors:        allowed-methods:        - "*"
        allowed-origins:        - "*"
        allowed-headers:        - "*"
      authwhitelist: "/oidc-support**"
      basic:
        jdbc:
          enable: true
          usersByUsernameQuery: "select name as username,user_password as password,enabled from basic_auth_clients where name = ?"
          authoritiesByUsernameQuery: "select name as username,'ADMIN' as authority from basic_auth_clients where name = ?"
        enable: true
        realm: v2solve
        users:
          - username: admin 
            password: system
            roles: superuser
          - username: app_onboarder 
            password: system
            roles: superuser
logging:  level:    com:
      v2solve:
        app:
          security: INFO
server:
  port: 9570      